---
AllCops:
  TargetRubyVersion: "2.7"
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "spec/db/contentful_migrations/*.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - "spec/**/*_spec.rb"

