---
AllCops:
  TargetRubyVersion: "2.7"
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "Guardfile"
    - "bin/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "test/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - config/routes.rb
    - spec/**/*_spec.rb

